# Generated by Django 3.1.7 on 2021-04-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.IntegerField()),
                ('stname', models.CharField(max_length=70)),
                ('stuemail', models.EmailField(max_length=70)),
                ('stpass', models.CharField(max_length=70)),
            ],
        ),
    ]
